from __future__ import annotations

from typing import Any

WEB_VIOLATIONS = [
    "VIOL_HTTP_PROTOCOL_VIOLATION",
    "VIOL_EVASION",
    "VIOL_SQL_INJECTION",
    "VIOL_XSS",
]

API_VIOLATIONS = [
    "VIOL_JSON_MALFORMED",
    "VIOL_PARAMETER_VALUE_METACHAR",
    "VIOL_OPEN_API_VIOLATION",
]


def build_easy_policy(
    name: str,
    app_type: str = "web",
    mode: str = "transparent",
    staging: bool = True,
    server_technologies: list[str] | None = None,
    disabled_signature_ids: list[int] | None = None,
) -> dict[str, Any]:
    if app_type not in {"web", "api"}:
        raise ValueError("type must be web or api")
    if mode not in {"transparent", "blocking"}:
        raise ValueError("mode must be transparent or blocking")

    violations = API_VIOLATIONS if app_type == "api" else WEB_VIOLATIONS
    technologies = server_technologies or []
    signatures = disabled_signature_ids or []
    policy: dict[str, Any] = {
        "policy": {
            "name": name,
            "applicationLanguage": "utf-8",
            "enforcementMode": mode,
            "template": {
                "name": "POLICY_TEMPLATE_API_SECURITY"
                if app_type == "api"
                else "POLICY_TEMPLATE_RAPID_DEPLOYMENT"
            },
            "blockingSettings": {
                "violations": [
                    {
                        "name": violation,
                        "alarm": True,
                        "block": mode == "blocking",
                    }
                    for violation in violations
                ]
            },
            "signature-settings": {
                "signatureStaging": staging,
            },
            "server-technologies": [
                {
                    "serverTechnologyName": technology,
                }
                for technology in technologies
            ],
            "signatures": [
                {
                    "signatureId": signature_id,
                    "enabled": False,
                    "performStaging": staging,
                }
                for signature_id in signatures
            ],
            "description": "Generated by f5-waf quickstart. Review and tune before production.",
        }
    }

    if app_type == "api":
        policy["policy"]["apiProtection"] = {
            "enableJsonValidation": True,
            "enableXmlValidation": False,
            "enforceContentType": True,
            "validateParameters": True,
        }

    return policy
